### ISSUE TITLE
SLF4J error

### ISSUE THREAD

**Issue by SturmB** [Dansoftowner/jSystemThemeDetector#11]
I appear to be getting a non-fatal error with this library. Starting up my app with `OSThemeDetector.registerListener()` in the `main()` method gives me this:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by anonymousaga** [comment]
I'm getting this exact same error too.

**Comment by anonymousaga** [comment]
One question: If I don't want any logger at all, as I don't need logs, would it be better to let this error continue and let the logger be non-operational? For me, the fewer logs and residual data, the better.

**Comment by Dansoftowner** [comment]
Well, if you don't want any logs at all, you can ignore the error.
I don't recommend you to do this because if jSystemThemeDetector fails and logs some error, you won't see it.

I think you should configure Logback and set the default logger level to `ERROR`, so you won't see any useless debugging/informational logs, just the important ones.
